services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: flask-backend
    ports:
      - "5000:5000"  # Expose backend port
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0  # Environment variable for Redis
    depends_on:
      - redis
    networks:
      - backend-frontend-network

  redis:
    image: "redis:6.2"
    container_name: redis
    ports:
      - "6379:6379"  # Expose Redis port
    networks:
      - backend-frontend-network

networks:
  backend-frontend-network:
    driver: bridge
